/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.senai.estudante.df.view;

import br.senai.estudante.df.util.Help;
import br.senai.estudante.df.util.Language;
import lombok.extern.log4j.Log4j2;

import javax.swing.*;

/**
 *
 * @author luan
 */
@Log4j2
public class MainView extends javax.swing.JFrame {

    /** Creates new form App */
    public MainView() {
        log.info("App view");
        initComponents();
        language();
    }

    private void language() {
        this.setTitle(Language.text("main"));
        mnManage.setText(Language.text("manage"));
        mniClient.setText(Language.text("client"));
        mniCar.setText(Language.text("car"));
        mniOccurrence.setText(Language.text("occurrence"));
        mnHelp.setText(Language.text("help"));
        mniHelp.setText("<html><b>?</b> " + Language.text("help"));
        mniAbout.setText("   " + Language.text("about"));
        mnTools.setText(Language.text("tools"));
        mniReport.setText(Language.text("report"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        mnbMenu = new javax.swing.JMenuBar();
        mnManage = new javax.swing.JMenu();
        mniClient = new javax.swing.JMenuItem();
        mniCar = new javax.swing.JMenuItem();
        mniOccurrence = new javax.swing.JMenuItem();
        mnTools = new javax.swing.JMenu();
        mniReport = new javax.swing.JMenuItem();
        mnHelp = new javax.swing.JMenu();
        mniHelp = new javax.swing.JMenuItem();
        mniAbout = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnManage.setText("Gerenciar");

        mniClient.setText("Cliente");
        mniClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniClientActionPerformed(evt);
            }
        });
        mnManage.add(mniClient);

        mniCar.setText("Automovel");
        mniCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCarActionPerformed(evt);
            }
        });
        mnManage.add(mniCar);

        mniOccurrence.setText("Ocorrencias");
        mniOccurrence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniOccurrenceActionPerformed(evt);
            }
        });
        mnManage.add(mniOccurrence);

        mnbMenu.add(mnManage);

        mnTools.setText("Ferramentas");

        mniReport.setText("Relatorio");
        mniReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniReportActionPerformed(evt);
            }
        });
        mnTools.add(mniReport);

        mnbMenu.add(mnTools);

        mnHelp.setText("Ajuda");

        mniHelp.setText("<html> <b>?</b> Ajuda");
        mniHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniHelpActionPerformed(evt);
            }
        });
        mnHelp.add(mniHelp);

        mniAbout.setText("  Sobre");
        mniAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAboutActionPerformed(evt);
            }
        });
        mnHelp.add(mniAbout);

        mnbMenu.add(mnHelp);

        setJMenuBar(mnbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniClientActionPerformed
        new ClientView().setVisible(true);
    }//GEN-LAST:event_mniClientActionPerformed

    private void mniCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCarActionPerformed
        new CarView().setVisible(true);
    }//GEN-LAST:event_mniCarActionPerformed

    private void mniOccurrenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniOccurrenceActionPerformed
        new OccurrenceView().setVisible(true);
    }//GEN-LAST:event_mniOccurrenceActionPerformed

    private void mniHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniHelpActionPerformed
        Help.help();
    }//GEN-LAST:event_mniHelpActionPerformed

    private void mniAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAboutActionPerformed
        log.info("About view");
        JOptionPane.showMessageDialog(this,
                "<html>" +
                "<center>Projeto Seguradora</center>" +
                "<br>" +
                Language.text("teacher") + ": Willians <br>" +
                Language.text("madeBy") + ": Luan Mateus <br>" +
                "<br>" +
                Language.text("contact") + ": luan.n@df.estudante.senai.br" +
                "</html>", Language.text("about"), JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mniAboutActionPerformed

    private void mniReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniReportActionPerformed
        new ReportView().setVisible(true);
    }//GEN-LAST:event_mniReportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu mnHelp;
    private javax.swing.JMenu mnManage;
    private javax.swing.JMenu mnTools;
    private javax.swing.JMenuBar mnbMenu;
    private javax.swing.JMenuItem mniAbout;
    private javax.swing.JMenuItem mniCar;
    private javax.swing.JMenuItem mniClient;
    private javax.swing.JMenuItem mniHelp;
    private javax.swing.JMenuItem mniOccurrence;
    private javax.swing.JMenuItem mniReport;
    // End of variables declaration//GEN-END:variables

}
